package net.stella;

public enum JobStatus {
	RECEIVED_JOB_REQUEST,
	INITIAL_INSPECTION_SCHEDULED,
    INITIAL_INSPECTION_COMPLETED,
    MEASUREMENTS_TAKEN,
    MATERIALS_CALCULATED,
    COST_ESTIMATE_PREPARED,
    ESTIMATE_REVIEWED,
    ESTIMATE_SENT_TO_CLIENT,
    CLIENT_FEEDBACK_RECEIVED,
    ESTIMATE_ADJUSTED,
    JOB_APPROVED,
    JOB_REJECTED
}
